<table border="0" cellpadding="0" cellspacing="0" class="mcnCaptionRightContentOuter" width="100%">
  <tbody><tr>
    <td valign="top" class="mcnCaptionRightContentInner" style="padding:0 9px ;">
      <table align="left" border="0" cellpadding="0" cellspacing="0" class="mcnCaptionRightImageContentContainer">
        <tbody><tr>
          <td class="mcnCaptionRightImageContent" valign="top">
            <a href="*|CAMPAIGN_LINK|*" title="" class="" target="_blank">
              <img alt="" src="*|CAMPAIGN_IMAGE_URL|*" width="264" style="max-width:800px;" class="mcnImage">
            </a>
          </td>
        </tr></tbody>
			</table>
      <table class="mcnCaptionRightTextContentContainer" align="right" border="0" cellpadding="0" cellspacing="0" width="264">
        <tbody><tr>
          <td valign="top" class="mcnTextContent">
            <center>
              <h2 class="null" dir="ltr" style="text-align: left;"><span style="font-size:24px">*|CAMPAIGN_TITLE|*</span></h2>
              <h3 class="null" dir="ltr" style="text-align: left;">*|CALL_TO_ACTION|*</h3>
              <p dir="ltr" style="text-align: left;">*|DO_IT_BODY|*</p>
              <p dir="ltr" style="text-align: left;"><strong>*|FAQ_HEADER|*</strong>: *|FAQ_BODY|*</p>
            </center>
            <center>
              <table border="0" cellpadding="0" cellspacing="0" class="emailButton" style="border-radius:3px; background-color:#23b7fb;">
                <tbody>
                  <tr>
                    <td align="center" class="emailButtonContent" style="padding-top:16px; padding-right:16px; padding-bottom:16px; padding-left:16px;" valign="middle"><a href="*|CAMPAIGN_LINK|*" style="color:#FFFFFF; font-family:Helvetica, Arial, sans-serif; font-size:16px; font-weight:bold; text-decoration:none;" target="_blank">DID IT? PROVE IT</a>
										</td>
                  </tr>
                </tbody>
              </table>
            </center>
          </td>
        </tr></tbody>
			</table>
    </td>
  </tr></tbody>
</table>
	