<table border="0" cellpadding="0" cellspacing="0" width="600" id="templateColumns">
  <tr>
    <td align="left" valign="top" class="columnsContainer" width="50%">	

      <table border="0" cellpadding="0" cellspacing="0" width="100%" class="templateColumn">
        <tr>
          <td valign="top" class="leftColumnContainer">
            <table border="0" cellpadding="0" cellspacing="0" width="100%" class="mcnCaptionBlock">
              <tbody class="mcnCaptionBlockOuter">
                <tr>
                  <td class="mcnCaptionBlockInner" valign="top" style="padding:9px;">
                    <table align="left" border="0" cellpadding="0" cellspacing="0" class="mcnCaptionBottomContent" width="false">
                      <tbody>
                        <tr>
                          <td class="mcnCaptionBottomImageContent" align="left" valign="top" style="padding:0 9px 9px 9px;">
                            <img alt="" src="*|CAMPAIGN_IMAGE_URL|*" width="264" style="max-width:300px;" class="mcnImage">
                          </td>
                        </tr>
                        <tr>
                          <td class="mcnTextContent" valign="top" style="padding:0 9px 0 9px;" width="264"></td>
                        </tr>
                      </tbody>
                    </table>
                  </td>
                </tr>
              </tbody>
            </table>
          </td>
        </tr>
      </table>

    </td>
    <td align="left" valign="top" class="columnsContainer" width="50%">
      <table border="0" cellpadding="0" cellspacing="0" width="100%" class="templateColumn">
        <tr>
          <td valign="top" class="rightColumnContainer">
  
            <table border="0" cellpadding="0" cellspacing="0" width="100%" class="mcnTextBlock">
              <tbody class="mcnTextBlockOuter">
                <tr>
                  <td valign="top" class="mcnTextBlockInner">
                    
                    <table align="left" border="0" cellpadding="0" cellspacing="0" width="300" class="mcnTextContentContainer">
                      <tbody>
                        <tr>
                          <td valign="top" class="mcnTextContent" style="padding-top:9px; padding-right: 18px; padding-bottom: 9px; padding-left: 18px;">
                            <h2 class="null">*|CAMPAIGN_TITLE|*</h2>
                            <h3 class="null">*|CAMPAIGN_CALL_TO_ACTION|*</h3>
                            <p>*|CAMPAIGN_PROBLEM_FACT|*</p>
                            <p>*|CAMPAIGN_SOLUTION_FACT|*</p>
    
                            <table border="0" cellpadding="0" cellspacing="0" class="mcnButtonBlock" width="100%">
                              <tbody class="mcnButtonBlockOuter">
                                <tr>
                                  <td align="center" class="mcnButtonBlockInner" style="padding-top:0; padding-right:18px; padding-bottom:18px; padding-left:18px;" valign="top">
                                    <table border="0" cellpadding="0" cellspacing="0" class="mcnButtonContentContainer" style="border-top-left-radius: 5px;border-top-right-radius: 5px;border-bottom-right-radius: 5px;border-bottom-left-radius: 5px;background-color: #23B8FC;">
                                      <tbody>
                                        <tr>
                                          <td align="center" class="mcnButtonContent" style="font-family: Arial; font-size: 16px; padding: 15px;" valign="middle">
                                            <a class="mcnButton " href="*|CAMPAIGN_LINK|*" style="font-weight: bold;letter-spacing: -0.5px;line-height: 100%;text-align: center;text-decoration: none;color: #FFFFFF;" target="_blank" title="DID IT? PROVE IT">DID IT? PROVE IT!</a>
                                          </td>
                                        </tr>
                                      </tbody>
                                    </table>
                                  </td>
                                </tr>
                              </tbody>
                            </table>
    
                          </td>
                        </tr>
                      </tbody>
                    </table>
                  
                  </td>
                </tr>
              </tbody>
            </table>
            
          </td>
        </tr>
      </table>

    </td>
  </tr>
</table>