                    <!-- BEGIN BODY // -->
                    <table border="0" cellpadding="0" cellspacing="0" width="600" id="templateBody">
                      <tr>
                        <td valign="top" class="bodyContainer" style="padding: 0 18px;">

												  *|CAMPAIGNS|*

												</td>
                      </tr>
                    </table>
                    <!-- // END BODY -->