										<!-- BEGIN FOOTER // -->
										<table border="0" cellpadding="0" cellspacing="0" width="600" id="templateFooter">
										  <tr>
												<td valign="top" class="footerContainer" style="padding-bottom:9px;">
														
													*|FOOTER_BYLINE|*
													*|FOOTER_COPY|*
													
												</td>
										  </tr>
										</table>
										<!-- // END FOOTER -->