										<!-- BEGIN PREHEADER // -->
										<table border="0" cellpadding="0" cellspacing="0" width="600" id="templatePreheader">
											<tr>
												<td valign="top" class="preheaderContainer" style="padding-top:9px;">

													<table border="0" cellpadding="0" cellspacing="0" width="100%" class="mcnTextBlock">
														<tbody class="mcnTextBlockOuter">
															<tr>
																<td valign="top" class="mcnTextBlockInner">

																	<table align="left" border="0" cellpadding="0" cellspacing="0" width="100%" class="mcnTextContentContainer">
																		<tbody>
																			<tr> 
																				<td align="left" valign="top" class="mcnTextContent" style="padding-top:9px; padding-left:18px; padding-bottom:9px; padding-right:0;">
																					<div dir="ltr">HereÕs how to crush it -- even harder than you already are.</div>
																				</td>
																				<td align="right" valign="top" class="mcnTextContent" style="padding-top:9px; padding-right:18px; padding-bottom:9px; padding-left:0;">
																					<a href="http://dosomething.org" style="text-align: right;" target="_blank"><img align="none" height="35" src="https://gallery.mailchimp.com/47b90314b0f78c04132888344/images/DoSomething_logo_transparent.png" style="opacity: 0.9; width: 44px; height: 35px; float: right; margin: 0px;" width="44"></a>
																				</td>
																			</tr>
																		</tbody>
																	</table>

																</td>
															</tr>
														</tbody>
												  </table>

											  </td>
										  </tr>
									  </table>
									  <!-- // END PREHEADER -->