													<!-- FOOTER_COPY -->
												  <table border="0" cellpadding="0" cellspacing="0" width="100%" class="mcnTextBlock">
														<tbody class="mcnTextBlockOuter">
														  <tr>
																<td valign="top" class="mcnTextBlockInner">
																  <table align="left" border="0" cellpadding="0" cellspacing="0" width="600" class="mcnTextContentContainer">
																		<tbody><tr>
																		  <td valign="top" class="mcnTextContent" style="padding-top:9px; padding-right: 18px; padding-bottom: 9px; padding-left: 18px;">
																				<em>Copyright © *|CURRENT_YEAR|* <a href="https://www.dosomething.org/" style="color: #23b7fb; text-decoration: none;">DoSomething.org</a>, All rights reserved.</em>
																		  </td>
																		</tr></tbody>
																  </table>
																</td>
														  </tr>
														</tbody>
												  </table>
													<!-- // FOOTER_COPY END -->