                    <!-- BEGIN HEADER // -->
                    <table border="0" cellpadding="0" cellspacing="0" width="600" id="templateHeader">
                      <tr>
                        <td valign="top" class="headerContainer">
												  <table border="0" cellpadding="0" cellspacing="0" width="100%" class="mcnBoxedTextBlock">
														<tbody class="mcnBoxedTextBlockOuter">
															<tr>
																<td valign="top" class="mcnBoxedTextBlockInner">
																	<table align="left" border="0" cellpadding="0" cellspacing="0" width="600" class="mcnBoxedTextContentContainer">
																		<tbody><tr>
																			<td style="padding-top:9px; padding-bottom:9px;">
																				<table border="0" cellpadding="18" cellspacing="0" class="mcnTextContentContainer" width="100%" style="background-color:#4e2b63">
																					<tbody><tr>
																						<td valign="top" class="mcnTextContent" style="color: white;">
																							<h2 style="margin: 0;"><span style="color: white; font-size: 34px;">Ready to rock your campaigns?</span></h2>
																							You signed up for these campaigns. Score! Now use our pro tips to rock them and send pics of your impact.
																						</td>
																					</tr></tbody>
																				</table>
																			</td>
																		</tr></tbody>
																	</table>
																</td>
															</tr>
														</tbody>
                          </table>
												</td>
                      </tr>
                    </table>
                    <!-- // END HEADER -->